import Vue from 'vue';import Router from 'vue-router';import store from '@/store'// 导入进度条import NProgress from 'nprogress';import 'nprogress/nprogress.css';// 个人中心import Message from './message';// 首页import Home from './home';//个人信息修改import PersonalInfo from './personalInfo'// 日历import Calendar from './workbench/calendar';// 公告import Notice from './workbench/notice';// 404import Error404 from './404';// 知识库import Catalog from './knowledgeBase/catalog'import Content from './knowledgeBase/content'import Search from './knowledgeBase/search'// 系统管理import SystemUser from './system/user';import SystemRole from './system/role';import SystemRoleAllocation from './system/role/allocation';import SystemRolePermission from './system/role/permission';import SystemMenu from './system/menu';import SystemDepartment from './system/department';import SystemPost from './system/post';import SystemDictionaries from './system/dictionaries';import SystemConfig from './system/sysconfig';import SystemLoginfo from './system/loginfo';import SystemArea from './system/area';import SystemBulletin from './system/bulletin';// 工作流import Instance from './process/Instance';import Modal from './process/modal';import AllPending from './process/allpending';import Pending from './process/pending';// 自定义表单import CustomerForm from './customerForm/home'import FormList from './customerForm'import FormManage from './customerForm/manage'import AddForm from './customerForm/addForm'import EditForm from './customerForm/editForm'import BindForm from './customerForm/bindForm'import Sublist from './customerForm/sublist'// 图表import Charts from './charts'// 轮播图import banner from './banner'import Data from './data'import Designer from './designer'import Qr from './qr'//生成
import GoodsData from './GoodsData';
import Goods from './Goods';
import GoodsLabel from './GoodsLabel';
import GoodsLabels from './GoodsLabels';
Vue.use(Router);const routerMap = {    '/kb-catalog': Catalog,    '/kb-content': Content,    '/kb-search': Search,    '/system-user': SystemUser,    '/system-role': SystemRole,    '/system-role-allocation': SystemRoleAllocation,    '/system-role-permission': SystemRolePermission,    '/system-menu': SystemMenu,    '/system-department': SystemDepartment,    '/system-post': SystemPost,    '/system-dictionaries': SystemDictionaries,    '/system-config': SystemConfig,    '/system-loginfo': SystemLoginfo,    '/system-area': SystemArea,    '/system-bulletin': SystemBulletin,    '/system-bulletin': SystemBulletin,    '/process-Instance': Instance,    '/process-modal': Modal,    '/process-pending': AllPending,    '/workSpace': Pending,    '/form-customer': CustomerForm,    '/form-list': FormList,    '/form-manage': FormManage,    '/form-add': AddForm,    '/form-edit': EditForm,    '/form-bind': BindForm,    '/banner': banner,    '/error': Error404,}let routes = [    {        path: '/',        redirect: '/home',    },    {        path: '/formApp',        title: '表单',        meta: { title: '表单' },        component: () =>            import( /* webpackChunkName: "login" */ '@/components/common/FormApp')    },    {        path: '/login',        title: '登录',        meta: { title: '登录' },        component: () =>            import( /* webpackChunkName: "login" */ '@/components/common/Login')    },    {        path: '/ForgotPassword',        title: '忘记密码',        meta: { title: '忘记密码' },        component: () =>            import( /* webpackChunkName: "login" */ '@/components/common/ForgotPassword')    },    {        path: '/',        redirect: '/home',        component: () =>            import( /* webpackChunkName: "layout" */ '@/components/common/Layout'),        meta: {            title: '首页',            requireAuth: true // 判断是否需要登录        },        children: [            Home,            Message,            Calendar,            PersonalInfo,            Notice,            Qr,            // 新增表单            AddForm,            // 编辑表单            EditForm,            // 设计表单            CustomerForm,            // 绑定流程            BindForm,            Pending,            Data,            Designer,            SystemRolePermission,            // 子表            Sublist,
            //生成
            GoodsData,
            Goods,
            GoodsLabel,
            GoodsLabels,
        ]    }];const router = new Router({    mode: 'hash',    base: process.env.BASE_URL,    routes: routes});// 使用钩子函数对路由进行权限跳转router.beforeEach((to, from, next) => {    NProgress.start();    document.title = sessionStorage.getItem('documentTitle') ? sessionStorage.getItem('documentTitle') : '';    const token = sessionStorage.getItem('token');    if (to.path == '/ForgotPassword') {        next();        return false;    }    if (!token && to.path == '/home') {        next('/login');    } else {        next();    }});router.afterEach(() => {    NProgress.done();});export function initDynamicRoutes() {    const currentRoutes = router.options.routes    const rightList = store.state.rightList    rightList.forEach((item, index) => {        if (item.children) {            item.children.forEach(item => {                const itemRule = routerMap[item.formType]                itemRule && currentRoutes[4].children.push(itemRule)            })        } else {            const itemRule = routerMap[item.formType]            itemRule && currentRoutes[4].children.push(itemRule)        }    })    if (rightList.length != 0) {        // 最后push404页面        const itemRule = routerMap['/error']        currentRoutes[4].children.push(itemRule)        router.addRoutes(currentRoutes)    }    console.log(currentRoutes);}export default router